### ISSUE TITLE
Java 17 upgrade is missing for this library. 

### ISSUE THREAD

**Issue by nagabhushanraju** [bobaikato/cutils#221]
Can the utility be updated in iterations of Java upgrade to most recent version. We did use this library and are missing developer who can upgrade it😄

**Comment by bobaikato** [comment]
Are you facing challenges while utilising the Library on a Java version beyond `Java 8`? 

The current design of the library is tailored to function seamlessly with `Java 8` for compatibility across higher Java versions. However, upgrading to `Java 17` will result in incompatibility with lower Java versions.
